// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Timora.Blog.Data;

#nullable disable

namespace Timora.Blog.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251016182028_AddCategoriesAndProfiles")]
    partial class AddCategoriesAndProfiles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("Timora.Blog.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Yaşam Tarzı ve Kişisel Gelişim",
                            Slug = "yasam-tarzi-ve-kisisel-gelisim"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Yemek ve Beslenme",
                            Slug = "yemek-ve-beslenme"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Seyahat ve Keşif",
                            Slug = "seyahat-ve-kesif"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Moda ve Stil",
                            Slug = "moda-ve-stil"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Teknoloji ve İnceleme",
                            Slug = "teknoloji-ve-inceleme"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sağlık ve Fitness",
                            Slug = "saglik-ve-fitness"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Hobi ve Sanat",
                            Slug = "hobi-ve-sanat"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Eğitim ve Kariyer",
                            Slug = "egitim-ve-kariyer"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Edebiyat ve Kitap",
                            Slug = "edebiyat-ve-kitap"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Ev ve Dekorasyon",
                            Slug = "ev-ve-dekorasyon"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Tüm Yazılar",
                            Slug = "tum-yazilar"
                        });
                });

            modelBuilder.Entity("Timora.Blog.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CoverImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("Timora.Blog.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirebaseUid")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Profession")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirebaseUid");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Timora.Blog.Models.Post", b =>
                {
                    b.HasOne("Timora.Blog.Models.UserProfile", "Author")
                        .WithMany("Posts")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Timora.Blog.Models.Category", "Category")
                        .WithMany("Posts")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Timora.Blog.Models.Category", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("Timora.Blog.Models.UserProfile", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
